# Copyright (c) 2026, Solrise and contributors
# For license information, please see license.txt
"""Turn resolution and the pending-intent store (docs/12 sections 5.2 and 6.2).

``chat/nlp.py`` turns one line of text into a closed intent and knows nothing about
Frappe. This is the Frappe-aware half of the intent engine:

* it learns the deployment's real naming-series prefixes from DocType metadata, so
  ``ISS-00042`` resolves without the model being asked anything;
* it keeps the half-finished intent in Redis between turns (15 minute TTL), and
  merges the widget's structured slot answers into it;
* it decides whether the turn is ready to execute, needs one more question, or
  should be handed to the model as a last resort.

Two things deliberately live elsewhere: nothing here touches a record (that is
``chat/executor.py``) and nothing here decides permissions (that is
``chat/permissions.py``). ``resolve()`` returns an intent; the controller runs the
gates before anything happens.
"""

from __future__ import annotations

import json
import re

import frappe
from frappe import _
from frappe.utils import cint, cstr, flt

from solrise_erp.chat import nlp, registry, schema

PENDING_PREFIX = "solrise_chat_pending:"
PENDING_TTL = 900  # seconds; docs/12 section 5.2 pins this at 15 minutes.

# Words that answer a pending confirmation when they arrive as text rather than as
# the widget's control action. Deliberately exact, and only consulted when a
# pending intent is actually waiting.
YES_WORDS = ("yes", "y", "yeah", "confirm", "confirmed", "proceed", "ok", "okay", "do it")
NO_WORDS = ("no", "n", "cancel", "stop", "abort", "never mind", "nevermind")

# Actions that name one existing record and cannot work without it.
RECORD_ACTIONS = ("update", "delete", "submit", "cancel", "approve")

# A process-local fallback for the pending store, used only when the cache is
# unreachable. It is not shared between workers, so it is a degraded
# single-worker experience rather than a crash - and a lost pending intent only
# makes the chat ask again.
_LOCAL_PENDING = {}


# --------------------------------------------------------------------------- #
# Vocabulary derived from metadata
# --------------------------------------------------------------------------- #
def prefixes():
	"""Naming-series prefixes this deployment really uses (docs/12 section 5.2).

	``nlp.parse`` matches several series by default; this refines them with the
	literal part of each addressable DocType's ``naming_series`` options, and falls
	back to the registry's list for the DocTypes that are named by the user or by
	a field. Memoised per request, because it reads metadata for every DocType.
	"""
	memo = getattr(frappe.local, "solrise_chat_prefixes", None)
	if memo is not None:
		return memo

	merged = dict(registry.PREFIXES)
	for doctype in registry.ACTION_REGISTRY:
		try:
			meta = frappe.get_meta(doctype)
			if meta is None:
				continue
			for prefix in _series_prefixes(meta):
				merged[prefix] = doctype
		except Exception:
			# One unreadable DocType must not cost the whole vocabulary: the
			# registry's own prefixes still resolve the common records.
			continue

	try:
		frappe.local.solrise_chat_prefixes = merged
	except Exception:
		pass
	return merged


def _series_prefixes(meta):
	"""The literal prefixes a DocType's naming series can produce."""
	try:
		get_field = getattr(meta, "get_field", None)
		options = ""
		if callable(get_field):
			df = get_field("naming_series")
			if df is not None:
				options = str(getattr(df, "options", "") or "")
		if not options:
			# `format:ISS-{#####}` carries its prefix in autoname instead.
			autoname = str(getattr(meta, "autoname", "") or "")
			if autoname.startswith("format:"):
				options = autoname.split(":", 1)[1]
	except Exception:
		return []

	found = []
	for line in options.splitlines():
		# "HR-LAP-.YYYY.-" -> "HR-LAP-"; the placeholder and everything after it is
		# generated by Frappe and is not part of what a user types.
		match = re.match(r"^\s*([A-Za-z][A-Za-z0-9_\-]*)", line)
		if match:
			found.append(match.group(1))
	return found


def my_tasks_doctypes(settings=None):
	"""The DocTypes "my tasks" searches, from Solrise Settings or the registry."""
	configured = _setting(settings, "chat_my_tasks_doctypes")
	if configured:
		names = [name.strip() for name in re.split(r"[\n,]+", str(configured)) if name.strip()]
		if names:
			return names
	return list(registry.MY_TASKS_DOCTYPES)


# --------------------------------------------------------------------------- #
# The pending-intent store
# --------------------------------------------------------------------------- #
def get_pending(session_id):
	"""The intent this session left half-finished, or ``None``."""
	key = _key(session_id)
	if not key:
		return None
	try:
		value = frappe.cache().get_value(key)
	except Exception:
		value = _LOCAL_PENDING.get(key)
	return value if isinstance(value, dict) else None


def remember_pending(session_id, parsed):
	"""Store a half-finished intent for the next turn.

	``set_value`` does not refresh the per-request memo ``get_value`` reads, so the
	memo is dropped first - otherwise a second turn in the same process (the
	console, and any test) would read the *previous* intent back (docs/12 section
	5.5). Production turns are separate requests, so this only matters there.
	"""
	key = _key(session_id)
	payload = _serialisable(parsed)
	if not key or payload is None:
		return
	try:
		cache = frappe.cache()
		cache.delete_value(key)
		cache.set_value(key, payload, expires_in_sec=PENDING_TTL)
	except Exception:
		_LOCAL_PENDING[key] = payload


def clear_pending(session_id):
	"""Drop the pending intent for this session. Safe to call when there is none."""
	key = _key(session_id)
	if not key:
		return
	_LOCAL_PENDING.pop(key, None)
	try:
		frappe.cache().delete_value(key)
	except Exception:
		pass


# --------------------------------------------------------------------------- #
# Resolution
# --------------------------------------------------------------------------- #
def resolve(message=None, action=None, payload=None, session_id=None, settings=None,
            user=None):
	"""Resolve one turn into an intent, a question, or a clarification.

	Returns a dict with ``doctype``/``action``/``record``/``urgency``/``transition``
	``/``fields``/``scope``/``slots``/``confidence``/``confirmed``/``turn`` plus one
	of ``cancelled`` or ``needs_clarification``. ``needs_clarification`` means the
	turn must not execute: ``question`` (a widget question payload, when the turn is
	waiting on a field) and/or the caller's own reply applies.
	"""
	message = (message or "").strip()
	action = (action or "").strip()
	payload = _clean_payload(payload)
	pending = get_pending(session_id)

	# -- control actions from the widget, and their typed equivalents ----------
	if action == "__cancel__" or (not action and pending and _is_no(message)):
		clear_pending(session_id)
		return _cancelled(pending)
	if action == "__confirm__" or (not action and pending and _is_yes(message)):
		return _resume(pending, payload, confirmed=True, settings=settings)

	# -- a structured answer to the question we asked last turn ---------------
	if not message and not action:
		if not pending:
			return _clarify(
				_("Pick one of the options below, or describe what you need."),
			)
		resumed = _resume(pending, payload, settings=settings)
		if resumed.get("needs_clarification"):
			return resumed
		return _advance(resumed, settings=settings)

	intent = None
	if message:
		intent = _parse(message, settings=settings, user=user)
	else:
		intent = nlp.quick_action(action, actions=registry.ACTION_REGISTRY)

	if intent is None:
		return _clarify(
			_("I didn't catch that. Pick one of the options below, or describe what you need."),
			raw=message or action,
		)

	# A fresh intent continues an earlier one when it names the same DocType and
	# either repeats the action or leaves it out ("ISS-00042" after "delete ...").
	# Anything else is a new conversation and starts the turn count over.
	merging = bool(
		pending and not intent.get("record") and intent.get("doctype")
		and intent["doctype"] == pending.get("doctype")
		and intent.get("action") in (None, pending.get("action"))
	)
	if merging:
		intent = _merge(pending, intent)
	else:
		intent["turn"] = 1

	intent["session_id"] = session_id

	if not intent.get("doctype") or not intent.get("action"):
		# `parse` reported the DocType but no verb ("leave application"): reading is
		# the safe default, and it is the only default that cannot mutate anything.
		if intent.get("doctype") and "read" in registry.ACTION_REGISTRY.get(intent["doctype"], []):
			intent["action"] = "read"
		else:
			return _clarify(
				_("Do you want to look something up or create something? Pick an option below."),
				parsed=intent,
			)
	if intent["action"] not in registry.ACTION_REGISTRY.get(intent["doctype"], []):
		return _clarify(
			_("I cannot do that with {0} from here. Pick one of the options below.").format(
				intent["doctype"]
			),
			parsed=intent,
		)

	if merging:
		# Answers are only read back mid-conversation, so a payload invented on a
		# first turn can never make the chat describe a field before the permission
		# gate has had its say (docs/12 section 7.1, gates 4 before 5).
		intent = _apply_payload(intent, payload)
		if intent.get("needs_clarification"):
			return intent
	return _advance(intent, settings=settings)


def _parse(message, settings=None, user=None):
	"""Deterministic parse first; the model only as a validated last resort."""
	intent = nlp.parse(
		message,
		prefixes=prefixes(),
		actions=registry.ACTION_REGISTRY,
		my_tasks=my_tasks_doctypes(settings),
	)
	if intent.get("doctype"):
		return intent
	return _fallback(message, settings=settings, user=user)


def _fallback(message, settings=None, user=None):
	"""Ask the model for a structured intent, then validate it field by field.

	The model is an untrusted hint: ``nlp.validate_proposal`` drops an unknown
	DocType, an unknown action, or an action the registry does not allow for that
	DocType, so a proposal can never name something the deterministic path could
	not (docs/12 section 1.3). Any failure degrades to "no intent".
	"""
	if not _setting(settings, "chat_enable_llm_fallback"):
		return None
	try:
		from solrise_erp.assistant import engine

		if engine.rate_limited(user or frappe.session.user):
			return None
		proposal = engine.propose_intent(message, user=user)
	except Exception:
		_log_error("could not ask the model for an intent")
		return None
	validated = nlp.validate_proposal(
		proposal, prefixes=prefixes(), actions=registry.ACTION_REGISTRY
	)
	if not validated:
		return None
	validated["module"] = None
	return validated


# --------------------------------------------------------------------------- #
# Turning an intent into the next question, or into something executable
# --------------------------------------------------------------------------- #
def _advance(intent, settings=None):
	"""Settle the intent: what is still missing, or is it ready to execute?

	The fields a write still needs are returned as ``intent["missing"]`` rather than
	asked about here. Asking is the controller's job, after the permission gate: a
	prompt for a field of a DocType the user may not create would otherwise leak
	metadata ahead of the decision that matters (docs/12 section 7.1, gate 5 after
	gate 4).
	"""
	intent["needs_clarification"] = False
	intent["question"] = None
	intent["question_sentence"] = None
	intent["missing"] = []

	if cint(intent.get("turn")) > (cint(_setting(settings, "chat_max_slot_turns")) or 4):
		# The loop guard (docs/12 section 7.5): stop asking rather than ping-pong.
		return _ask_again(
			intent,
			_("I'm not getting the details I need. Please try again in one sentence."),
		)

	doctype = intent["doctype"]
	action = intent["action"]
	fields = intent.get("fields") or {}

	if action in RECORD_ACTIONS and not intent.get("record"):
		return _ask_again(
			intent,
			_("Which {0} should I work on? Give me its ID, for example ISS-00001.").format(doctype),
		)
	if action == "update" and not fields:
		return _ask_again(
			intent, _("What should I change on {0}?").format(intent.get("record")),
		)

	if action in ("create", "update"):
		# Only a write has required slots to fill: asking a reader for a `subject`
		# before it may list anything would be the obvious wrong turn here.
		intent["missing"] = schema.missing_required(doctype, fields, settings)
		if not intent["missing"] and action == "create" and not fields:
			# "create a lead" has no required slot to prompt for, so without this the
			# executor would insert a nameless record. Ask for the field Frappe itself
			# uses to show the record instead.
			field = _name_field(doctype)
			if field:
				intent["missing"] = [field]

	return intent


# Fields Frappe fills itself, so they can never be the answer to "what is it called?".
UNASKABLE = ("read_only", "fetch_from", "default")


def _name_field(doctype):
	"""The DocType's own title field, when a user can fill it in."""
	try:
		meta = frappe.get_meta(doctype)
	except Exception:
		return None
	name = cstr(getattr(meta, "title_field", "") or "")
	if not name:
		return None
	try:
		df = meta.get_field(name)
	except Exception:
		return None
	if df is None or cstr(df.fieldtype) in schema.LAYOUT_FIELDTYPES or name in schema.AUTO_FIELDS:
		return None
	if any(getattr(df, attribute, None) for attribute in UNASKABLE):
		return None
	return {
		"fieldname": name,
		"label": cstr(df.label or "") or name,
		"fieldtype": cstr(df.fieldtype or "Data"),
		"options": cstr(df.options or ""),
		"reqd": 0,
	}


def _ask_again(intent, sentence):
	"""A clarification that needs no input control - only words."""
	intent["needs_clarification"] = True
	intent["question"] = None
	intent["question_sentence"] = sentence
	remember_pending(intent.get("session_id"), intent)
	return intent


def _apply_payload(intent, payload):
	"""Fold this turn's structured answers into the intent, one field at a time.

	An answer that fails the field's own rules does not enter the intent: the turn
	becomes the same question again with the reason in front of it (docs/12 section
	5.4), so a bad Link or Date answer is rejected without a traceback.
	"""
	if not payload:
		return intent

	fields = dict(intent.get("fields") or {})
	for fieldname, value in payload.items():
		if fieldname in ("record", "doctype", "action"):
			continue
		result = schema.validate_value(intent["doctype"], fieldname, value)
		if not result.get("ok"):
			field = _field_for(intent["doctype"], fieldname)
			intent["needs_clarification"] = True
			intent["question"] = field
			intent["question_sentence"] = question_reply(
				field, result.get("error") or _("That value did not work.")
			)
			remember_pending(intent.get("session_id"), intent)
			return intent
		fields[fieldname] = result.get("value")
	intent["fields"] = fields
	intent["slots"] = dict(fields)
	return intent


def _field_for(doctype, fieldname):
	"""The widget's question payload for one field, rebuilt for a re-ask."""
	try:
		df = frappe.get_meta(doctype).get_field(fieldname)
	except Exception:
		return {"fieldname": fieldname, "label": fieldname, "fieldtype": "Data", "options": ""}
	return schema.question_for({
		"fieldname": fieldname,
		"label": (df.label if df is not None else None) or fieldname,
		"fieldtype": (df.fieldtype if df is not None else None) or "Data",
		"options": (df.options if df is not None else None) or "",
		"reqd": 1,
	})


def question_reply(field, error=None):
	"""What the chat says above a question control.

	A plain text field answers itself - the widget already prints the label as the
	input's caption - so only a hint (a Link ID, a list of options, a date format)
	or a rejection earns a sentence.
	"""
	hint = schema.next_question(field) if field.get("fieldtype") in (
		"Link", "Select", "Autocomplete", "Date", "Datetime", "Dynamic Link",
	) else ""
	if error and hint:
		return "{0} {1}".format(error, hint)
	if error:
		return str(error)
	return hint


# --------------------------------------------------------------------------- #
# Resuming and merging
# --------------------------------------------------------------------------- #
def _resume(pending, payload, confirmed=False, settings=None):
	"""Continue the stored intent, optionally as a confirmation."""
	intent = dict(pending)
	intent["confirmed"] = bool(confirmed)
	intent["turn"] = cint(intent.get("turn")) + 1
	intent["session_id"] = pending.get("session_id")
	intent["needs_clarification"] = False
	intent["question"] = None
	intent["question_sentence"] = None
	if confirmed or not payload:
		# A confirmation carries no new values: the answers were merged as they
		# arrived, and the widget resends the whole bag on every turn.
		return intent
	return _apply_payload(intent, payload)


def _merge(pending, intent):
	"""Keep the answers already collected when the same operation is re-stated."""
	merged = dict(intent)
	merged["doctype"] = intent.get("doctype") or pending.get("doctype")
	merged["action"] = intent.get("action") or pending.get("action")
	fields = dict(pending.get("fields") or {})
	fields.update(intent.get("fields") or {})
	merged["fields"] = fields
	merged["slots"] = dict(fields)
	for key in ("record", "urgency", "transition", "scope", "module"):
		merged[key] = intent.get(key) or pending.get(key)
	merged["turn"] = cint(pending.get("turn")) + 1
	merged["confirmed"] = False
	return merged


def _cancelled(pending):
	return {
		"raw": "",
		"doctype": (pending or {}).get("doctype"),
		"action": (pending or {}).get("action"),
		"record": (pending or {}).get("record"),
		"urgency": None,
		"transition": None,
		"fields": {},
		"scope": None,
		"slots": {},
		"confidence": 1.0,
		"confirmed": False,
		"turn": cint((pending or {}).get("turn")),
		"cancelled": True,
		"needs_clarification": False,
	}


def _clarify(sentence, parsed=None, raw=None):
	intent = dict(parsed or {})
	intent.update({
		"raw": raw if raw is not None else intent.get("raw"),
		"confidence": flt(intent.get("confidence")),
		"cancelled": False,
		"needs_clarification": True,
		"question": intent.get("question"),
		"question_sentence": sentence,
		"fields": dict(intent.get("fields") or {}),
		"slots": dict(intent.get("slots") or intent.get("fields") or {}),
		"confirmed": False,
	})
	return intent


# --------------------------------------------------------------------------- #
# Small helpers
# --------------------------------------------------------------------------- #
def _key(session_id):
	session_id = str(session_id or "").strip()
	return (PENDING_PREFIX + session_id) if session_id else None


def _clean_payload(payload):
	"""The widget sends its collected answers as a JSON string."""
	if isinstance(payload, dict):
		return {str(k): v for k, v in payload.items() if v not in (None, "")}
	if not payload:
		return {}
	if isinstance(payload, str):
		try:
			loaded = json.loads(payload)
		except ValueError:
			return {}
		if isinstance(loaded, dict):
			return {str(k): v for k, v in loaded.items() if v not in (None, "")}
	return {}


def _serialisable(intent):
	"""Only the keys a later turn needs, in a form Redis can hand back."""
	if not isinstance(intent, dict):
		return None
	keep = ("raw", "doctype", "action", "record", "urgency", "transition", "fields",
	        "scope", "module", "slots", "confidence", "turn", "session_id")
	payload = {key: intent.get(key) for key in keep if key in intent}
	try:
		json.dumps(payload, default=str)
	except Exception:
		return None
	return payload


def _is_yes(message):
	text = nlp.normalize(message)
	return bool(text) and text in YES_WORDS


def _is_no(message):
	text = nlp.normalize(message)
	return bool(text) and text in NO_WORDS


def _setting(settings, fieldname):
	"""One Solrise Settings value, or ``None`` when it cannot be read."""
	try:
		if settings is not None:
			value = settings.get(fieldname) if hasattr(settings, "get") \
				else getattr(settings, fieldname, None)
			if value not in (None, ""):
				return value
		return frappe.db.get_single_value("Solrise Settings", fieldname)
	except Exception:
		return None


def _log_error(subject):
	try:
		frappe.log_error(title="Solrise chat: {0}".format(subject), message=frappe.get_traceback())
	except Exception:
		pass
